Update aws-api-import.sh to work on non-GNU
`readlink -f` is specific to GNU coreutils and generates messages like
this on Mac OS X:

     $ ./src/aws-apigateway-importer/aws-api-import.sh
     readlink: illegal option -- f
     usage: readlink [-n] [file ...]
     Error: Unable to access jarfile ./target/aws-apigateway-importer-1.0.3-SNAPSHOT-jar-with-dependencies.jar

Instead we use perl, which is pretty much guaranteed to be installed
everywhere.